### PR TITLE
added support for <script type="text/ng-template"> templates

### LINKED ISSUE #31: need a way to inject template in script tag format
I find this library a nice idea & soling the problem.

for some reason my templates are in the script tag format, which then include & pick up by PHP.

```
  <script type="text/ng-template" id="templateId.html">
    <p>This is the content of the template</p>
  </script>
```

with ng-html2js, the whole thing will be treated as the template itself
i.e.  $templateCache.get('templateId.html') will get the script tags as well

so the approach perhaps a script tag regex is good enough

### PR DESCRIPTION
**Pull request by arkarkark**
fixes https://github.com/karma-runner/karma-ng-html2js-preprocessor/issues/31

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks @arkarkark and sorry for the late feedback, it would be great if you could

* remove the changes to `.travis.yml` and `package.json` 
* squash all commits into one and follow our commit message [convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html)
* rebase onto the latest master to resolve the merge issues

then I can get this in finally

**Comment by arkarkark** [comment]
heh, yah, I'll get to it but likely not for a few weeks. Will do all you suggest though.That'll be in another PR so closing this one.

**Comment by erickcsh** [comment]
@arkarkark is there any chance you'll get into this soon?

**Comment by arkarkark** [comment]
It has passed the year anniversary of me saying I'll get to it. I've had it in my todo unread email queue for ages, I will try and get to it. sorry.

**Comment by arkarkark** [comment]
I had a go... I got it to work, but couldn't get the tests working how it looked like they wanted to. I'm going to give up on this, you can use it as a starting block to start again if you want.

**Pull request closed without merging**
