### PR TITLE
Added further setup instructions

### PR DESCRIPTION
**Pull request by levithomason**
This branch is intended to help resolve some of the issues raised in #15.  The documentation seems to make some assumptions that a developer new to Karma would not make.  Also, there is isn't much in the way of instructions for debugging once the developer runs into an issue.

Suggested improvements:

- [ ] Add debug information
- [x] Add note regarding plugins config

more?

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks @levithomason are you planning on adding more in here?

**Comment by levithomason** [comment]
Boy, I let this one slip and I've lost context by now.  I'd merge as is. My day job is now React land so I don't know if/when I'll get back to this.

**Comment by ilanbiala** [comment]
@Dignifiedquire the docs are quite unclear and there is no example app. Can we get some more documentation for this plugin?

**Comment by levithomason** [comment]
@Dignifiedquire I've signed the CLA.

**Comment by ilanbiala** [comment]
@Dignifiedquire I still think an example app would be really useful in showing how the paths match the file structure and what things can and cannot be done.

**Comment by Dignifiedquire** [comment]
@ilanbiala sure it would be nice, but I currently don't have one and I'm not really using this module, so maybe someone else, who is actually using it, could contribute one.

**Comment by Dignifiedquire** [comment]
@levithomason thanks :octocat:

**Comment by ilanbiala** [comment]
@Dignifiedquire who actively maintains this module and uses it then?

**Pull request merged**
