### PR TITLE
Removing the html2js name overwrite

### PR DESCRIPTION
**Pull request by aorielly**
This causes issues when you need to use both pre processors

### CODE REVIEW

**Comment by omichelsen** [comment]
Will this be merged and released soon? Quite a few issues on this: https://github.com/karma-runner/karma-ng-html2js-preprocessor/issues/65, https://github.com/karma-runner/karma-ng-html2js-preprocessor/issues/43

**Comment by bimusiek** [comment]
When do you plan to merge this? I just spent 1 hour debugging why karma-fixtures does not work and it happened that this is the reason. :+1:

**Comment by Dignifiedquire** [comment]
Sorry for the delay, could you please update the commit message to follow our [convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html) then I'll put this into the next release.

**Comment by aorielly** [comment]
I signed it!

I have also updated the commit message

**Comment by Dignifiedquire** [comment]
Thanks

**Pull request merged**
